mdns = {
	'demo' : [
		'*',
	],
	'emb6' : [
        'mdns',
        'sock',
        'rpl',
        'ipv6',
        'sicslowpan',
        'dllsec',
        'dllc',
        'mac',
        'phy',
        'framer',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('DEMO_USE_MDNS',1),
		('RESOLV_CONF_SUPPORTS_MDNS',1),
		('NET_USE_RPL',1),
	],
# GCC flags
	'CFLAGS' : [
	]
}

Return('mdns')