udp_alive = {
	'demo' : [
	],
	'emb6' : [
		'sock',
		'rpl',
		'ipv6',
		'sicslowpan',
		'dllsec',
		'dllc',
		'mac',
		'framer',
		'phy',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('DEMO_USE_UDPALIVE',1),
		('NET_USE_RPL',1),
	],
# GCC flags
	'CFLAGS' : [
	]	
}

Return('udp_alive')
