udp_alive = {
	'demo' : [
	],
	'emb6' : [
		'rpl',
		'ipv6',
		'sicslowpan',
		'nullmac',
		'802154framer',
	],
	'utils' : [
		'*',
	],
# C global defines
	'defines' : [
		('DEMO_USE_UDPALIVE',1),
		('NET_USE_RPL',1),
	],
# GCC flags
	'cflags' : [
	]	
}

Return('udp_alive')