emb6 = {
	'common' : [
		'*',
	],
	'coap' : [
		'apl/er-coap/*',
		'apl/rest-engine/*',
	],
	'lwm2m' : [
		'apl/lwm2m-core/*',
	],
	'mqtt' : [
		'apl/mqtt/*',
	],
	'dtls' : [
		'net/dtls/*',
		'net/dtls/aes/*',
		'net/dtls/ecc/*',
		'net/dtls/sha2/*',
	],
	'mle' : [
		'mle/*',
	],
	'rip' : [
		'net/rip/resources/*',
		'net/rip/*',
	],
	'mdns' : [
		'apl/dns/*',
	],
	'sock' : [
		'tport/*',
	],
	'ipv6' : [
		'net/ipv6/*',
	],
	'ipv6mc' : [
		'net/ipv6/multicast/*',
	],
	'rpl' : [
		'net/rpl/*',
	],
	'sicslowpan':  [
		'net/sicslowpan/*',
	],
	'slip' : [
		'net/slip/*',
	],
# new netstack drivers
	'dllsec' : [
		'dll/dllsec/*',
	],
	'dllc' : [
		'dll/dllc/*',
	],
	'mac' : [
		'dll/mac/*',
	],
	'framer' : [
		'dll/framer/*',
	],
	'phy' : [
		'phy/*',
	],

# C global defines
	'defines' : [
	],
# GCC flags
	'cflags' : [
	]	
}

Return('emb6')