emb6 = {
	'common' : [
		'*',
	],
	'coap' : [
		'apl/er-coap/*',
		'apl/rest-engine/*',
	],
	'lwm2m' : [
		'apl/lwm2m-core/*',
	],
	'mqtt' : [
		'apl/mqtt/*',
	],
	'sock' : [
		'tport/*',
	],
	'ipv6' : [
		'net/ipv6/*',
	],
	'ipv6mc' : [
		'net/ipv6/multicast/*',
	],
	'rpl' : [
		'net/rpl/*',
	],
	'sicslowpan':  [
		'net/sicslowpan/*',
	],
	'slip' : [
		'net/slip/*',
	],
# new netstack drivers
	'llsec' : [
		'dll/llsec/*',
	],
	'llc' : [
		'dll/llc/*',
	],
	'mac' : [
		'dll/mac/*',
	],
	'framer' : [
		'dll/framer/*',
	],
	'phy' : [
		'phy/*',
	],
	'lpr' : [
		'phy/lpr/*',
	],
# C global defines
	'defines' : [
	],
# GCC flags
	'cflags' : [
	]	
}

Return('emb6')