dtls = {
	'demo' : [
		'*',
	],
	'emb6' : [
        'coap',
        'dtls',
        'sock',
        'rpl',
        'ipv6',
        'sicslowpan',
        'dllsec',
        'dllc',
        'mac',
        'framer',
        'phy',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('DEMO_USE_DTLS',1),
		('NET_USE_RPL',1),
		('WITH_CONTIKI',1),
	],
# GCC flags
	'CFLAGS' : [
	]
}

Return('dtls')
