mdns = {
	'demo' : [
		'*',
	],
	'emb6' : [
		'mdns',
		'sock',
		'rpl',
		'ipv6',
		'sicslowpan',
		'dllsec',
		'dllc',
		'mac',
		'phy',
		'framer',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('EMB6_INIT_ROOT',1),
		('DEMO_USE_MDNS',1),
		('CONF_USE_SERVER',1),
		('RESOLV_CONF_SUPPORTS_MDNS',1),
		('NET_USE_RPL',1),
	],
# GCC flags
	'CFLAGS' : [
	]
}

Return('mdns')