extif = {
	'demo' : [
	],
	'emb6' : [
		'sock',
		'ipv6',
		'sicslowpan',
		'slip',
		'dllsec',
		'dllc',
		'mac',
		'framer',
		'phy',
	],
	'utils' : [
		'*',
	],
# C global defines
	'defines' : [
		('DEMO_USE_EXTIF',1),
	],
# GCC flags
	'cflags' : [
	]	
}

Return('extif')