coap = {
	'demo' : [
		'*',
	],
	'emb6' : [
		'coap',
		'sock',
		'rpl',
		'ipv6',
		'sicslowpan',
		'llsec',
		'llc',
		'mac',
		'framer',
		'phy',
		'lpr',
	],
	'utils' : [
		'*',
	],
# C global defines
	'defines' : [
		('DEMO_USE_COAP',1),
		('NET_USE_RPL',1),
	],
# GCC flags
	'cflags' : [
	]	
}

Return('coap')