/**
 * @file	  packetbuf_ext.h
 * @date	  02.06.2016
 * @author 	Phuong Nguyen
 */

#ifndef PACKETBUF_EXT_H_
#define PACKETBUF_EXT_H_

enum {
  /* MAC PIB attributes */
  PACKETBUF_ATTR_MAC_MAX_BE = PACKETBUF_ATTR_MAX,
  PACKETBUF_ATTR_MAC_MIN_BE,
  PACKETBUF_ATTR_MAC_MAX_CSMA_BACKOFFS,
  PACKETBUF_ATTR_MAC_PAN_ID,
  PACKETBUF_ATTR_MAC_SHORT_ADDR,  /* TODO */
  PACKETBUF_ATTR_MAC_ACK_WAIT_DURATION,
  PACKETBUF_ATTR_MAC_FCS_LEN,
  PACKETBUF_ATTR_MAC_UNIT_BACKOFF_PERIOD,

  /* PHY PIB attributes */
  PACKETBUF_ATTR_PHY_MAX_PACKET_SIZE,
  PACKETBUF_ATTR_PHY_TURNAROUND_TIME,
  PACKETBUF_ATTR_PHY_SYMBOLS_PER_OCTET,
  PACKETBUF_ATTR_PHY_PREAMBLE_SYMBOL_LEN,
  PACKETBUF_ATTR_PHY_SHR_DURATION,
  PACKETBUF_ATTR_PHY_SYMBOL_PERIOD,

  /* Addressing modes */
  PACKETBUF_ATTR_ADDR_SENDER_MODE,
  PACKETBUF_ATTR_ADDR_RECEIVER_MODE,

  /* Maximum extended attribute */
  PACKETBUF_EXT_ATTR_MAX,
};

/* Number of extended attributes */
#define PACKETBUF_NUM_EXT_ATTRS   (PACKETBUF_EXT_ATTR_MAX - PACKETBUF_ATTR_MAX)

#endif /* PACKETBUF_EXT_H_ */
