thread_sink = {
	'demo' : [
	],
	'emb6' : [
		'sock',
		'rpl',
		'ipv6',
		'sicslowpan',
		'dllsec',
		'mle',
		'dllc',
		'mac',
		'framer',
		'phy',
		'nullmac',
		'802154framer',
		'ipv6mc',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('DEMO_USE_THREAD_SINK',1),
		#('DEMO_USE_UDPALIVE',1),
		('NET_USE_RPL',1),
	],
# GCC flags
	'CFLAGS' : [
	]	
}

Return('thread_sink')
