thread = {
	'demo' : [
	],
	'emb6' : [
		'coap',
		'sock',
		'ipv6',
		'sicslowpan',
		'dllsec',
		'dllc',
		'mac',
		'framer',
		'phy',
		'ipv6mc',
		'mle',
		'thread',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('DEMO_USE_THREAD',1),
#		('CONF_USE_SERVER',1),
		('THRD_USE_ROUTING',1),
	],
# GCC flags
	'CFLAGS' : [
	]	
}

Return('thread')