routeroot = {
	'demo' : [
	],
	'emb6' : [
		'sock',
		'rpl',
		'ipv6',
		'sicslowpan',
		'llsec',
		'nullmac',
		'802154framer',
		'ipv6mc',
		'rip',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('DEMO_USE_ROUTE_ROOT',1),
		#('DEMO_USE_UDPALIVE',1),
		('NET_USE_RPL',1),
	],
# GCC flags
	'CFLAGS' : [
	]	
}

Return('routeroot')
