udp_socket = {
	'demo' : [
	   '../*',
	],
	'emb6' : [
		'sock',
		'rpl',
		'ipv6',
		'sicslowpan',
		'dllsec',
		'dllc',
		'mac',
		'framer',
		'phy',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('EMB6_INIT_ROOT',1),
		('NET_USE_RPL',1),
		('DEMO_USE_UDP_SOCKET_SIMPLE',1),
		('DEMO_UDP_SOCKET_SIMPLE_ROLE_SERVER', 1)
	],
# GCC flags
	'CFLAGS' : [
	]
}

Return('udp_socket')
