thrd_coap = {
	'demo' : [
	],
	'emb6' : [
		'rpl',
		'coap',
		'sock',
		'ipv6',
		'sicslowpan',
		'dllsec',
		'dllc',
		'mac',
		'framer',
		'phy',
		'ipv6mc',
		'mle',
		'rip',
	],
	'utils' : [
		'*',
	],
# C global defines
	'CPPDEFINES' : [
		('DEMO_USE_THRD_COAP',1),
		('CONF_USE_SERVER',1),
		('THRD_USE_RIP',1),
	],
# GCC flags
	'CFLAGS' : [
	]	
}

Return('thrd_coap')